#!/bin/bash
## UCSC rmsk output open-4.0.3-20130422 ## http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz
## Usage (using UCSC rmsk output open-4.0.320130422): curl -s http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz | zcat | ./rmsk2bed.sh
## Convert to GTF: awk -vOFS="\t" '{ print $1,"hg38_rmsk","exon",($2+1),$3,$5,$6,".","gene_id \""$10"\"; transcript_id \""$4"\"; family_id \""$11"\"; class_id \""$12"\";" }'
## Classes to filter for RNA-seq analysis: (Low_complexity|Simple_repeat|rRNA|scRNA|srpRNA|tRNA)

gawk -vOFS="\t" 'BEGIN {

  print "#chr\tstart\tend\trepName\tSWscore\tstrand\tmilliDiv\tmilliDel\tmilliIns\trepSubfamily\trepFamily\trepClass\trepStart\trepEnd\trepLeft\trepInstance"

} NR>3 {

  sw_score=$1
  millidiv=$2
  millidel=$3
  milliins=$4
  chr=$5
  start=$6-1
  end=$7
  strand=($9=="+" ? "+" : "-")
  subfam=$10
  repstart=(strand=="+" ? $12 : $14)
  if (repstart ~/\(/) gsub(/[\(\)]/,"",repstart)
  repstart-=1
  repend=$13
  repleft=(strand=="+" ? $14 : $12)
  if (repleft ~/\(/) {
    gsub(/[\(\)]/,"",repleft)
  }
  instance=$15

  if ($11~/\//) {
    split($11,fam,"/")
    class = fam[1]
    family = fam[2]
  } else {
    class = $11
    family = $11
  }

  sfarr[subfam]+=1
  repname=subfam"_l"sfarr[subfam]

  print chr,start,end,repname,sw_score,strand,millidiv,millidel,milliins,subfam,family,class,repstart,repend,repleft,instance

}'

